library(dslabs)
library(ggplot2)
library(dplyr)
data("gapminder")
years = c(1970, 1985, 1990, 2000, 2010)
countries = c("India", "China", "Singapore")
asia_info <- filter(gapminder, continent=='Asia', year%in%years, !is.na(infant_mortality), !is.na(gdp))
region_groups <- asia_info%>%group_by(region)
med_summary <- region_groups %>% filter(year==2010)%>%summarise(mean_age=mean(life_expectancy), mean_children=mean(fertility), mean_gdp=mean(gdp))
#plot_1 <- asia_info %>% ggplot(aes(infant_mortality, life_expectancy, colour=region)) + geom_point() + facet_wrap(~year)
#plot_2 <- asia_info %>% ggplot(aes(fertility, life_expectancy, colour=region)) + geom_point() + facet_wrap(~year)
#plot_3 <- asia_info %>% ggplot(aes(fertility, population, colour=region)) + geom_boxplot() + scale_y_log10() + facet_wrap(~year)
#print(plot_1)
#print(plot_2)
#print(plot_3)
ds_theme_set()
data_india_china <- filter(gapminder, country%in%countries)
print(data_india_china)
data_india_china %>% ggplot(aes(year, population)) + geom_line()  + facet_grid(~country)  
data_india_china %>% ggplot(aes(year, life_expectancy)) + geom_line() + facet_grid(~country)  