library(dslabs)
library(dplyr)
library(ggplot2)
data("gapminder")
ds_theme_set()
countries <- c("India", "Japan", "Germany", "United States", "China")
filtered_list <- gapminder %>% filter(country%in%countries)
filtered_list <- filtered_list %>% select(year, country, population, gdp, region)
filtered_list <- mutate(filtered_list, income_per_capita=gdp/population/365)
filtered_list %>% ggplot(aes(year, population, colour=country)) + geom_smooth() + scale_y_log10()
filtered_list %>% ggplot(aes(year, income_per_capita, colour=country)) + geom_smooth() + scale_y_log10()
